'use client';

import { useState } from 'react';
import { Edit3, Trash2 } from 'lucide-react';
import { useRouter } from 'next/navigation';
import ConfirmationDialog from '@/components/admin/ConfirmationDialog';

export default function EmployeeActions({ companyId, employee }: { companyId: number; employee: { id: number; name: string; email: string } }) {
  const [open, setOpen] = useState(false); const [confirmOpen, setConfirmOpen] = useState(false); const [name, setName] = useState(employee.name); const [email, setEmail] = useState(employee.email); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const router = useRouter();
  const save = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setError(''); const response = await fetch(`/api/proxy/companies/${companyId}/employees/${employee.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name, email }) }); setBusy(false); if (!response.ok) { setError((await response.json().catch(() => ({}))).message || 'Could not update employee'); return; } setOpen(false); router.refresh(); };
  const remove = async () => { setBusy(true); setError(''); const response = await fetch(`/api/proxy/companies/${companyId}/employees/${employee.id}`, { method: 'DELETE' }); setBusy(false); if (!response.ok) { setError((await response.json().catch(() => ({}))).message || 'Could not delete employee'); return; } setConfirmOpen(false); router.refresh(); };
  return <span style={{ display: 'flex', gap: 6 }}><button className="btn-secondary icon-button" onClick={() => { setError(''); setOpen(true); }} aria-label="Edit employee"><Edit3 size={14} /></button><button className="btn-secondary icon-button" onClick={() => { setError(''); setConfirmOpen(true); }} disabled={busy} aria-label="Delete employee"><Trash2 size={14} /></button>{open && <div className="glass-overlay" style={overlay} onClick={(e) => { if (e.target === e.currentTarget) setOpen(false); }}><form className="premium-card" style={dialog} onSubmit={save}><h3>Edit employee</h3><input className="input-field" value={name} onChange={e => setName(e.target.value)} required /><input className="input-field" type="email" value={email} onChange={e => setEmail(e.target.value)} required />{error && <p style={{ color: '#b42318' }}>{error}</p>}<div style={actions}><button type="button" className="btn-secondary" onClick={() => setOpen(false)}>Cancel</button><button className="btn-primary" disabled={busy}>Save</button></div></form></div>}{confirmOpen && <ConfirmationDialog title={`Delete ${employee.name}?`} description="The employee can only be removed when there is no order history attached to the record." confirmLabel="Delete employee" busy={busy} onConfirm={remove} onCancel={() => setConfirmOpen(false)} />}{error && !open && <div className="glass-overlay" style={overlay}><div className="premium-card" style={dialog}><h3>Employee could not be deleted</h3><p style={{ color: '#b42318' }}>{error}</p><button className="btn-primary" onClick={() => setError('')}>Close</button></div></div>}</span>;
}
const overlay = { position: 'fixed' as const, inset: 0, zIndex: 1000, display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 20, background: 'rgba(15,23,42,.35)' };
const dialog = { width: '100%', maxWidth: 400, display: 'grid', gap: 14 };
const actions = { display: 'flex', justifyContent: 'flex-end', gap: 10 };
